version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app
file_exists_behavior: OVERWRITE

hooks:

  BeforeInstall:
    - location: scripts/install_docker.sh
      runas: root

  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 8000
      runas: root
      
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 8000
      runas: root
  