version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - $GOLANGSKELETON_PORT/tcp
    ports:
      - "$GOLANGSKELETON_PORT:$GOLANGSKELETON_PORT"
    volumes:
      - go-modules:/go/pkg/mod
      
      
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    name: app_network

volumes:
  go-modules:
